### PR TITLE
Add questions related to testing

### PR DESCRIPTION
**Pull request by imGurpreetSK**

### CODE REVIEW

**Comment by codeOfRobin** [comment]
Heyo! gonna merge this as soon as I figure out how to integrate https://www.npmjs.com/package/alex into the CI.

**Comment by codeOfRobin** [comment]
Hey @GurpreetSK95 ! 👋 

I just added CI support (sorry it took so long, I was in London for a conference): https://github.com/codeOfRobin/Questions-to-ask-your-interviewer-iOS/pull/3

I'm not quite sure how I can trigger the CI other than by you making an empty commit(Sounds like a bad idea tbh, open to suggestions). Could you do that? I'll squash and merge once tests run.

**Comment by imGurpreetSK** [comment]
Hey! Had some more questions to add to the `people/teams` section  regarding remote-work/work from home(s). Would it be fine if I add a commit related to that in this branch(instead of the empty/hacky commit)?

**Comment by codeOfRobin** [comment]
Sure! That works. Merging.

**Pull request merged**
